### ISSUE TITLE
Extract comments

### ISSUE THREAD

**Issue by friep** [friep/vaccc19de#2]
Sometimes, the excel contains comments at the end of the "data sheet" that apply to some Bundesländer (indicated with ** after the name). It would be good to preserve them (at least the ones except the first *) and add them as an additional column `comment`. 

See `tests/testthat/test_data/impfquotenmonitoring.xlsx` for an example.

**Comment by favstats** [comment]
This [pull request](https://github.com/friep/vaccc19de/pull/3) should be able to handle any number of comments. 

I only just realized that you had suggested the name `comment` for the variable but I already had called it `bundesland_notes`. Feel free to change it as I don't feel super strongly about it and it might be a bit redundant because each row is already identified as an individual Bundesland.
